name: code_coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, bcmath
          coverage: xdebug

      - name: Install dependencies
        # working-directory: sample
        run: composer install --no-suggest --no-interaction --optimize-autoloader 
            #  composer require --dev rregeer/phpunit-coverage-check

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml
          log_junit: ./coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true

