name: code_coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build-test:
  #   name: CI Build
  #   runs-on: ubuntu-latest
  #   #2 strategy:
  #   #2   matrix:
  #   # 2    php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
  #   # 2    coverage: [false]
  #   # 2    experimental: [false]
  #   # 2    include:
  #   #  2     # Run code coverage on high/low PHP.
  #   #  2     - php: '5.5'
  #   #   2      coverage: true
  #   #  2       experimental: false
  #   #  2     - php: '8.1'
  #   #  2       coverage: true
  #   #  2       experimental: false

  #   # 2      # Experimental builds. These are allowed to fail.
  #   # 2      - php: '8.2'
  #   # 2        coverage: false
  #   #  2       experimental: true
    
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

  #   - name: Setup PHP with Xdebug
  #     uses: shivammathur/setup-php@v2
  #     with:
  #       php-version: '7.3'
  #       #2 coverage: xdebug
  #       coverage: none
  #       tools: cs2pr

  #   - name: Install dependencies with composer
  #     #2 run: composer update --no-ansi --no-interaction --no-progress
  #     uses: php-actions/composer@v6

  #   - name: Run tests with phpunit/phpunit
  #     # 2run: vendor/bin/phpunit 
  #     #2 --coverage-clover <coverage.xml>

  #     uses: php-actions/phpunit@v3
  #     #2  env:
  #     #2    XDEBUG_MODE: coverage
  #     #2  with:
  #     #2    bootstrap: vendor/autoload.php
  #     # 2   configuration: phpunit.xml
  #     # 2   php_extensions: xdebug
  #     # 2   args: tests --coverage-clover ./coverage.xml

  #   #2 - name: Check coding standards
  #   #2     # continue-on-error: true
  #   #2     run: ./vendor/bin/phpcs -s --report-full --report-checkstyle=./phpcs-report.xml

  #   #2 - name: Show PHPCS results in PR
  #   #2     run: cs2pr ./phpcs-report.xml

  #   - name: Send coverage report to Codecov
  #       # if: ${{ success() && matrix.coverage == true }}
  #       uses: codecov/codecov-action@v3
  #       with:
  #         files: ./coverage.xml
  #         fail_ci_if_error: true
  #         verbose: true
  #   #2 - name: Fix code coverage paths
  #   #2   run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

 test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, bcmath
          coverage: xdebug

      - name: Install dependencies
        # working-directory: sample
        run: composer install --no-suggest --no-interaction --optimize-autoloader 
             composer require --dev rregeer/phpunit-coverage-check

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover coverage.xml



      # - name: Run tests
      #   # working-directory: sample
      #   # run: phpdbg -qrr vendor/bin/phpunit --coverage-clover coverage.xml --check-version
      #   run:  vendor/bin/phpunit --coverage-clover coverageNew.xml 

      # - name: Fix code coverage paths
      #   run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
        #   version: "v0.1.15"
          files: coverage.xml
          verbose: true

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md




    
      # - name: Coverage Test
      #   uses: sourcetoad/phpunit-coverage-action@v1
      #   with:
      #     clover_report_path: output.xml
      #     min_coverage_percent: 80
      #     fail_build_on_under: true

      # name: Send coverage report to Codecov
      #   # if: ${{ success() && matrix.coverage == true }}
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./logs/clover.xml
      #     fail_ci_if_error: true
      #     verbose: true

      # - name: Coverage Test (Fail)
      #   uses: ./
      #   with:
      #     clover_report_path: ./output.xml
      #     min_coverage_percent: 100
      #     fail_build_on_under: false
