name: code_coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: CI Build
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    #     coverage: [false]
    #     experimental: [false]
    #     include:
    #       # Run code coverage on high/low PHP.
    #       - php: '5.5'
    #         coverage: true
    #         experimental: false
    #       - php: '8.1'
    #         coverage: true
    #         experimental: false

    #       # Experimental builds. These are allowed to fail.
    #       - php: '8.2'
    #         coverage: false
    #         experimental: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        # coverage: xdebug
        coverage: none
        tools: cs2pr

    - name: Install dependencies with composer
      # run: composer update --no-ansi --no-interaction --no-progress
      uses: php-actions/composer@v6

    - name: Run tests with phpunit/phpunit
      # run: vendor/bin/phpunit 
      # --coverage-clover <coverage.xml>

      uses: php-actions/phpunit@v3
       env:
         XDEBUG_MODE: coverage
       with:
         bootstrap: vendor/autoload.php
         configuration: phpunit.xml
         php_extensions: xdebug
         args: tests --coverage-clover ./coverage.xml

    # - name: Check coding standards
    #     # continue-on-error: true
    #     run: ./vendor/bin/phpcs -s --report-full --report-checkstyle=./phpcs-report.xml

    # - name: Show PHPCS results in PR
    #     run: cs2pr ./phpcs-report.xml

    - name: Send coverage report to Codecov
        # if: ${{ success() && matrix.coverage == true }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
    # - name: Fix code coverage paths
    #   run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
